ittool/urls.py
from django.urls import path
from .views import Index, Plugins, EternalArts, ShowPlugin, Downloads, About


app_name = 'ittool'
urlpatterns = [
    path('', Index.as_view(), name='index'),
    path('downloads/', Downloads.as_view(), name='downloads'),
    path('plugins/', Plugins.as_view(), name='plugins'),
    path('eternal-arts/', EternalArts.as_view(), name='eternal-arts'),
    path('about/', About.as_view(), name='about'),
    path('plugin/<slug>/', ShowPlugin.as_view(), name='plugin')
]

ittools/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from ittools import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('ittool.urls'))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

ittool/models.py
from django.db import models
from django.urls import reverse


class Plugin(models.Model):
    name = models.CharField(max_length=15, verbose_name='Name')
    icon = models.ImageField(upload_to="icons/%Y/%m/%d/",
                             blank=True, verbose_name='Icon')
    description = models.TextField(verbose_name='Description', max_length=180)
    dev_name = models.CharField(
        max_length=15, verbose_name='Developer name')
    date_added = models.DateTimeField(
        auto_now_add=True, verbose_name='Date added')
    version = models.CharField(max_length=10, verbose_name='Version')
    slug = models.SlugField(unique=True, verbose_name='URL')

    class Meta:
        verbose_name = 'Plugin'
        verbose_name_plural = 'Plugins'
        ordering = ['date_added', 'name']

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('ittool:plugin', kwargs={'slug': self.slug})


class ItToolsVersion(models.Model):
    name = models.CharField(max_length=255, verbose_name='Name')
    version = models.CharField(max_length=10, verbose_name='Version')
    version_type = models.CharField(max_length=20, verbose_name='Version Type')
    file = models.FileField(upload_to="files/%Y/%m/%d/", verbose_name='File')
    date_added = models.DateTimeField(
        auto_now_add=True, verbose_name='Date added')

    class Meta:
        verbose_name = 'ITTOOLS Version'
        verbose_name_plural = 'ITTOOLS Versions'
        ordering = ['-version']

ittool/views.py
from django.shortcuts import render, get_object_or_404
from django.views.generic import TemplateView, ListView, DetailView
from .models import Plugin, ItToolsVersion
from .utils import menu, str_queryset_to_list, list_to_queryset


# def index(request):
#     context = {'menu': menu, 'page_selected': -1}
#     return render(request, 'ittool/index.html', context)


class Index(TemplateView):
    template_name = 'ittool/index.html'

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)

        context['menu'] = menu
        context['page_selected'] = -1

        return context


# def plugins(request):
#     plugins = Plugin.objects.all()
#     if request.method == 'GET':
#         plugins_filter = request.GET.get('plugin_or_dev_name')
#         name_filter = request.GET.get('name_filter')
#         date_filter = request.GET.get('date_filter')
#         plugins_list = []
#         if plugins_filter:
#             for plugin in Plugin.objects.all():
#                 if plugins_filter.lower() in plugin.name.lower():
#                     plugins_list.append(plugin)
#                 elif plugins_filter.lower() in plugin.dev_name.lower():
#                     plugins_list.append(plugin)
#             plugins = list_to_queryset(Plugin, plugins_list)

#         if request.GET.get('past_plugins'):
#             past_plugins = list_to_queryset(
#                 Plugin, str_queryset_to_list(Plugin, request.GET.get('past_plugins')))
#             if name_filter:
#                 plugins = past_plugins.order_by(name_filter)
#             if date_filter:
#                 plugins = past_plugins.order_by(date_filter)

#     context = {'menu': menu, 'page_selected': 1, 'plugins': plugins}
#     return render(request, 'ittool/plugins.html', context)


class Plugins(ListView):
    model = Plugin
    template_name = 'ittool/plugins.html'
    context_object_name = 'plugins'

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)

        context['menu'] = menu
        context['page_selected'] = 1

        return context

    def get_queryset(self):
        plugins = Plugin.objects.all()
        if self.request.method == 'GET':
            plugins_filter = self.request.GET.get('plugin_or_dev_name')
            name_filter = self.request.GET.get('name_filter')
            date_filter = self.request.GET.get('date_filter')
            plugins_list = []
            if plugins_filter:
                for plugin in Plugin.objects.all():
                    if plugins_filter.lower() in plugin.name.lower():
                        plugins_list.append(plugin)
                    elif plugins_filter.lower() in plugin.dev_name.lower():
                        plugins_list.append(plugin)
                plugins = list_to_queryset(Plugin, plugins_list)

            if self.request.GET.get('past_plugins'):
                past_plugins = list_to_queryset(
                    Plugin, str_queryset_to_list(Plugin, self.request.GET.get('past_plugins')))
                if name_filter:
                    plugins = past_plugins.order_by(name_filter)
                if date_filter:
                    plugins = past_plugins.order_by(date_filter)

        return plugins


# def eternal_arts(request):
#     context = {'menu': menu, 'page_selected': 2}
#     return render(request, 'ittool/eternal_arts.html', context)


class EternalArts(TemplateView):
    template_name = 'ittool/eternal_arts.html'

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)

        context['menu'] = menu
        context['page_selected'] = 2

        return context


# def plugin(request, slug):
#     plugin = get_object_or_404(Plugin, slug=slug)

#     context = {'menu': menu, 'page_selected': -1, 'plugin': plugin}
#     return render(request, 'ittool/plugin.html', context)


class ShowPlugin(DetailView):
    model = Plugin
    context_object_name = 'plugin'
    template_name = 'ittool/plugin.html'
    slug_url_kwarg = 'slug'

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)

        context['menu'] = menu
        context['page_selected'] = -1

        return context


# def downloads(request):
#     versions = ItToolsVersion.objects.all()

#     context = {'menu': menu, 'page_selected': 0, 'versions': versions}
#     return render(request, 'ittool/downloads.html', context)


class Downloads(ListView):
    model = ItToolsVersion
    template_name = 'ittool/downloads.html'
    context_object_name = 'versions'

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)

        context['menu'] = menu
        context['page_selected'] = 0

        return context

    def get_queryset(self):
        return ItToolsVersion.objects.all()


# def about(request):
#     context = {'menu': menu, 'page_selected': 3}
#     return render(request, 'ittool/about.html', context)


class About(TemplateView):
    template_name = 'ittool/about.html'

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)

        context['menu'] = menu
        context['page_selected'] = 3

        return context

ittool/templates/ittool/about.html
{% extends 'ittool/base.html' %}
{% load static %}


{% block title %}ITTOOLS - About{% endblock title %}

{% block content %}
<img src="{% static 'ittool/images/code2.png' %}" class="background-image">
<div class="about">
    <p class="about-text">ITOOLS was developed by:</p>
    <p class="about-text">TheHakerTech (theaihopgg)</p>
    <p class="about-text">An72ty (an72_)</p>
    <br>
    <a class="about-text">The website was developed by:</a>
    <p class="about-text">An72ty (an72_)</p>
    <br>
    <p class="about-text">Above are the nicknames in github and in brackets the nicknames in discord</p>
</div>
{% endblock content %}

ittool/templates/ittool/base.html
{% load static %}

<!DOCTYPE html>
<html lang="ru">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <link rel="stylesheet" type="text/css" href="//fonts.googleapis.com/css?family=Comfortaa" />
    <link rel="stylesheet" type="text/css" href="{% static 'ittool/css/style.css' %}">
    <link rel="shortcut icon" href="{% static 'ittool/favicon.ico' %}" type="image/x-icon">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v6.2.1/css/all.css">
    <title>{% block title %}ITTOOLS{% endblock title %}</title>
</head>

<body>
    <div class="top-panel">
        <a class="top-panel-item logo" href="{% url 'ittool:index' %}">ITTOOLS</a>
        {% if menu %}
        {% for page in menu reversed %}
        {% if page.page_number != page_selected %}
        <a class="top-panel-item" href="{% url page.url %}">{{ page.title }}</a>
        {% else %}
        <a class="top-panel-item visited">{{ page.title }}</a>
        {% endif %}
        {% endfor%}
        {% else %}
        <a class="top-panel-item" href="{% url 'ittool:downloads' %}">Downloads</a>
        <a class="top-panel-item" href="{% url 'ittool:plugins' %}">Plugins</a>
        <a class="top-panel-item" href="{% url 'ittool:eternal-arts' %}">Eternal Arts</a>
        <a class="top-panel-item" href="{% url 'ittool:about' %}">About</a>
        {% endif %}
    </div>
    <div class="content-panel">{% block content %}{% endblock content %}</div>
</body>

<footer id="copyright">
    <a class="copyright">&copy; 2023 Eternal Arts</a>
    <a class="contact" href="{% url 'ittool:about' %}">Contacts</a>
</footer>

</html>

ittool/templates/ittool/downloads.html
{% extends 'ittool/base.html' %}


{% block title %}ITTOOLS - Downloads{% endblock title %}


{% block content %}
<p id="downloads-title">Download ITTOOLS</p>
{% for version in versions %}
<div class="ittools-version">
    <a class="purple-button" id="download" href="{{ version.file.url }}" download="{{ version.file.url }}">
        <i class="fa-solid fa-download fa-xl" style="color: #ffffff;"></i>
    </a>
    <a class="version-name">{{ version.name }}</a>
    <a class="version-type">{{ version.version_type }}</a>
    <a class="version-version">{{ version.version }}</a>
    <a class="version-date-added">{{ version.date_added|date:'d.m.Y' }}</a>
</div>
{% endfor %}
{% endblock content %}

ittool/templates/ittool/eternal_arts.html
{% extends 'ittool/base.html' %}
{% load static %}


{% block title %}ITTOOLS - Eternal Arts{% endblock title %}

{% block content %}
<div class="links">
    <p><a href="https://github.com/eternal-arts" class="link" target="_blank">GitHub</a></p>
    <p><a href="https://discord.gg/akHbNUgphK" class="link" target="_blank">Discord</a></p>
    <p><a href="#copyright" class="link">Copyright</a></p>
</div>

<div class="eternal-arts-info">
    <img class="eternal-arts-icon" src="{% static 'ittool/images/eternal_arts_icon.png' %}" alt="eternal arts icon">
    <p class="eternal-arts-info-title">Eternal Arts</p>
    <p class="eternal-arts-info-text">Eternal Arts is a small team of developer friends. We create mostly
        free and useful programs.
    </p>
    <p class="eternal-arts-info-text" id="count-of-members">At the time of the creation of the site (Aug 30, 2023),
        there
        are 7 people in the team<br>(below are the nicknames in github)</p>
    <div class="eternal-arts-info-list">
        <a>An72ty</a>
        <a>bleudev</a>
        <a>d1xus</a>
        <a>DarkSlipe</a>
        <a>kotazzz</a>
        <a>Kotella107</a>
        <a>moontr3</a>
        <a>TheHakerTech</a>
        <a>Wordexx</a>
    </div>
</div>
{% endblock content %}

ittool/templates/ittool/index.html
{% extends 'ittool/base.html' %}
{% load static %}


{% block content %}
<div class="preview">
    <img src="{% static 'ittool/images/code.jpg' %}" class="background-image">
    <p class="slogan">ITOOLS is a versatile solution for the IT industry: speed up project creation with a wide range of
        tools and capabilities!</p>

    <p class="short-description">It provides a wide range of tools and plugins that allow you to speed up and simplify
        the process of creating applications and websites.</p>

    <a href="{% url 'ittool:downloads' %}" class="purple-button">Download Latest</a>
</div>
<div class="description-block">
    <img src="{% static 'ittool/images/it_field.jpg' %}" class="description-image">

    <p class="description-text">The ITOOLS program is a powerful and versatile solution for the development of projects
        in the IT field. It provides a wide range of tools and plugins that allow you to speed up and simplify the
        process of creating applications and websites.</p>
</div>
<div class="description-block">
    <p class="description-text right">One of the main advantages of the program is the ability to install a variety of
        plugins
        developed by independent developers. These plugins can significantly expand the functionality of ITOOLS and add
        new features, for example, for working with databases, graphic design, testing and many others.</p>

    <img src="{% static 'ittool/images/directions.jpg' %}" class="description-image right">
</div>
<div class="description-block">
    <img src="{% static 'ittool/images/coder.jpg' %}" class="description-image">

    <p class="description-text" id="short">In general, ITOOLS is a powerful and flexible platform for project
        development, which
        allows you to improve the efficiency and quality of work in the field of IT.</p>
</div>
{% endblock content %}

ittool/templates/ittool/plugin.html
{% extends 'ittool/base.html' %}


{% block title %}ITTOOLS - {{ plugin.name }}{% endblock title %}


{% block content %}
<div class="plugin-large">
    {% if plugin.icon %}
    <img class="plugin-icon-large" src="{{ plugin.icon.url }}">
    {% endif %}
    <a class="plugin-name-large">{{ plugin.dev_name }}\{{ plugin.name }}</a>
    <a class="plugin-version-large">{{ plugin.version }}</a>
    <p class="plugin-description-large">{{ plugin.description }}</p>
    <a class="plugin-date-added-large">{{ plugin.date_added|date:'d.m.Y' }}</a>
</div>
{% endblock content %}

ittool/templates/ittool/plugins.html
{% extends 'ittool/base.html' %}

{% block title %}ITTOOLS - Plugins{% endblock title %}

{% block content %}
<form action="{% url 'ittool:plugins' %}" method="get">
    {% csrf_token %}
    <input type="text" name="plugin_or_dev_name" class="input-plugin-or-dev-name"
        placeholder="Write dev name or plugin name">
    <button class="purple-button" type="submit">Search</button>
</form>

<!-- <hr class="content-separator"> -->
<br>

<form action="{% url 'ittool:plugins' %}" method="get" class="input-filters">
    {% csrf_token %}
    <a class="title">Sort by</a>
    <p class="input-filters-label">Dev name
        <input type="checkbox" name="name_filter" id="dev-name" value="dev_name" class="input-filters-input">
    </p>

    <p class="input-filters-label">Name
        <input type="checkbox" name="name_filter" id="name" value="name" class="input-filters-input">
    </p>

    <p class="input-filters-label">First the new
        <input type="radio" name="date_filter" id="first-the-new" value="date_added" class="input-filters-input">
    </p>

    <p class="input-filters-label">First the old
        <input type="radio" name="date_filter" id="first-the-old" value="-date_added" class="input-filters-input">
    </p>

    <input type="hidden" name="past_plugins" value='{{ plugins }}'>

    <button class="purple-button" type="submit">Sort</button>
</form>
{% if plugins %}
{% for plugin in plugins %}
<div class="plugin">
    {% if plugin.icon %}
    <img class="plugin-icon" src="{{ plugin.icon.url }}">
    {% endif %}
    <a class="plugin-name" href="{{ plugin.get_absolute_url }}">{{ plugin.dev_name }}\{{ plugin.name }}</a>
    <a class="plugin-version">{{ plugin.version }}</a>
    <a class="plugin-date-added">{{ plugin.date_added|date:'d.m.Y' }}</a>
</div>
{% endfor %}
{% else %}
<p class="not-found-message">There're no any plugins</p>
{% endif %}
{% endblock content %}